name: drone_312
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - numpy>=2.0.0
  - scipy>=1.12.0
  - ipython>=8.20.0
  - matplotlib>=3.5.0
  - pandas>=2.1.0
  - seaborn>=0.13.0
  - pytest>=8.3.4
  - attrs>=23.1.0
  - flake8>=7.1.0
  - pip
